// lib/src/generators/test_orchestrator.dart

import 'dart:io';

import 'package:path/path.dart' as p;

import '../analyzers/feature_scanner.dart';
import '../analyzers/notifier_parser.dart';
import '../analyzers/state_parser.dart';
import '../models/notifier_info.dart';
import 'test_generator.dart';

/// Runs the feature scan and writes generated tests into
/// `test/unit/features`.
class TestOrchestrator {
  /// Creates an orchestrator for the given project.
  TestOrchestrator({
    required this.projectRoot,
    required this.packageName,
    this.dryRun = false,
    this.verbose = false,
    this.force = false,
    this.feature,
  });

  /// Absolute path to the project root.
  final String projectRoot;

  /// Package name used to build import paths.
  final String packageName;

  /// When `true`, generated files are not written to disk.
  final bool dryRun;

  /// When `true`, progress messages are emitted during execution.
  final bool verbose;

  /// When `true`, existing test files are overwritten even when they no
  /// longer carry the `GENERATED BY mogen_unit_tests` marker (i.e. they've
  /// been hand-edited or hand-written).
  final bool force;

  /// If non-null, only generate tests for this feature name.
  final String? feature;

  /// The marker every generated file starts with. A file that exists but
  /// lacks it is treated as hand-maintained and is not overwritten unless
  /// [force] is set.
  static const _generatedMarker = 'GENERATED BY mogen_unit_tests';

  /// Scans the project, parses notifiers and state models, and writes tests.
  Future<OrchestratorResult> run() async {
    final featuresRoot = p.join(projectRoot, 'lib', 'features');
    final testRoot = p.join(projectRoot, 'test');

    final scanner = FeatureScanner(featuresRoot: featuresRoot);
    final notifierParser =
        NotifierParser(projectRoot: projectRoot, packageName: packageName);
    final stateParser =
        StateParser(projectRoot: projectRoot, packageName: packageName);

    var bundles = scanner.scan();
    if (feature != null && feature!.isNotEmpty) {
      bundles = bundles.where((b) => b.featureName == feature).toList();
    }
    _log('Found ${bundles.length} feature(s)\n');

    final errors = <String>[];

    // ── First pass: parse every notifier and state file up front, match
    //    states immediately, and build the project-wide registry of notifier
    //    class → parsed info. The registry lets the generator resolve
    //    accurate imports for cross-notifier dependencies
    //    (ref.read(otherNotifierProvider)) even when the other notifier
    //    lives in a different feature, and generate runtime-safe mocks for
    //    them (real base class + stubbed build()).
    final parsedByBundle = <FeatureBundle, List<NotifierInfo>>{};
    final notifierIndex = <String, String>{};
    final notifierRegistry = <String, NotifierInfo>{};

    for (final bundle in bundles) {
      final states = stateParser.parseAll(bundle.stateFiles);

      final notifiers = <NotifierInfo>[];
      for (final notifierFile in bundle.notifierFiles) {
        try {
          for (var notifier in notifierParser.parse(notifierFile)) {
            notifier = notifier.withStateInfo(_matchState(notifier, states));
            notifiers.add(notifier);

            if (notifierRegistry.containsKey(notifier.className)) {
              stderr.writeln(
                '⚠️   Two notifiers share the class name '
                '${notifier.className} — keeping the first one '
                '(${notifierIndex[notifier.className]}) for dependency '
                'resolution; ${notifier.importPath} is shadowed.',
              );
            } else {
              notifierIndex[notifier.className] = notifier.importPath;
              notifierRegistry[notifier.className] = notifier;
            }
          }
        } catch (e, st) {
          final msg = 'Error in $notifierFile: $e\n$st';
          errors.add(msg);
          stderr.writeln('⚠️   $msg');
        }
      }
      parsedByBundle[bundle] = notifiers;
    }

    // Pass projectRoot so the generator can locate dependency source files
    // for signature resolution, plus the index/registry for cross-notifier
    // dependencies.
    final generator = TestGenerator(
      projectRoot: projectRoot,
      notifierIndex: notifierIndex,
      notifierRegistry: notifierRegistry,
    );

    int written = 0;
    int skipped = 0;

    // ── Second pass: generate test files.
    for (final bundle in bundles) {
      _log('📁  ${bundle.featureName}');

      for (final notifier in parsedByBundle[bundle] ?? const <NotifierInfo>[]) {
        if (notifier.stateInfo != null) {
          _log(
              '    ✅  ${notifier.className} → state: ${notifier.stateInfo!.className}');
        } else {
          _log('    ✅  ${notifier.className} (no state matched)');
        }

        final content = generator.generate(notifier);
        final outPath = p.join(
          testRoot,
          'unit',
          'features',
          bundle.featureName,
          '${_snake(notifier.className)}_test.dart',
        );

        if (dryRun) {
          _log('    [dry-run] → $outPath');
          skipped++;
        } else if (!force && _isHandMaintained(outPath)) {
          stderr.writeln(
            '⚠️   Skipped $outPath — the file exists without the '
            '"$_generatedMarker" marker, so it looks hand-maintained. '
            'Re-run with --force to overwrite it.',
          );
          skipped++;
        } else {
          _write(outPath, content);
          _log('    📝  → $outPath');
          written++;
        }
      }
      _log('');
    }

    return OrchestratorResult(
      featuresScanned: bundles.length,
      filesWritten: written,
      filesSkipped: skipped,
      errors: errors,
    );
  }

  /// `true` when a file already exists at [path] but doesn't carry the
  /// generated-file marker — i.e. overwriting it would destroy manual work.
  bool _isHandMaintained(String path) {
    final file = File(path);
    if (!file.existsSync()) return false;
    try {
      return !file.readAsStringSync().contains(_generatedMarker);
    } catch (_) {
      return true;
    }
  }

  StateInfo? _matchState(NotifierInfo n, List<StateInfo> states) {
    if (states.isEmpty) return null;

    if (n.stateType != null) {
      final match = states.firstWhere((s) => s.className == n.stateType,
          orElse: () => _none);
      if (!identical(match, _none)) return match;
    }

    final prefix =
        n.className.replaceAll(RegExp(r'(Notifier|Cubit|Bloc|ViewModel)$'), '');

    // Prefer the exact `${prefix}State` match before falling back to a
    // prefix search, whose result would otherwise depend on filesystem
    // enumeration order when multiple states share the same prefix
    // (e.g. `CartState` and `CartSummaryState` both matching `CartNotifier`).
    final exact = states.firstWhere((s) => s.className == '${prefix}State',
        orElse: () => _none);
    if (!identical(exact, _none)) return exact;

    for (final s in states) {
      if (s.className.startsWith(prefix)) return s;
    }

    return null;
  }

  static const _none =
      StateInfo(className: '__none__', importPath: '', fields: []);

  void _write(String path, String content) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
  }

  void _log(String msg) {
    if (verbose) stdout.writeln(msg);
  }

  /// Acronym-aware snake_case (`APIClient` → `api_client`), matching the
  /// generator's file-name convention.
  String _snake(String name) => name
      .replaceAllMapped(
        RegExp(r'([A-Z]+)([A-Z][a-z])'),
        (m) => '${m.group(1)}_${m.group(2)}',
      )
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (m) => '${m.group(1)}_${m.group(2)}',
      )
      .toLowerCase();
}

/// Summary of the results produced by a test generation run.
class OrchestratorResult {
  /// Number of features scanned.
  final int featuresScanned;

  /// Number of files successfully written.
  final int filesWritten;

  /// Number of files skipped (dry-run mode, or hand-maintained files
  /// protected from overwrite).
  final int filesSkipped;

  /// Errors encountered during generation.
  final List<String> errors;

  /// Creates a result summary.
  const OrchestratorResult({
    required this.featuresScanned,
    required this.filesWritten,
    required this.filesSkipped,
    required this.errors,
  });

  /// Returns `true` when the run produced one or more errors.
  bool get hasErrors => errors.isNotEmpty;
}
