// lib/src/generators/test_generator.dart

import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;

import '../models/notifier_info.dart';
import '../utils/method_call_detector.dart';
import '../utils/mock_value_generator.dart';

/// Generates a complete Mocktail + Riverpod test file for one [NotifierInfo].
///
/// Improvements:
///   - Only stubs methods actually called in the notifier
///   - Filters to only mock repository interfaces (not services)
///   - Generates generic repository return stubs for any feature
///   - Generates specific state field assertions (before/after)
///   - Imports only relevant domain repository interfaces
///   - Skips helper methods starting with 'p' (internal notifier extensions)
///   - Emits `any(named: 'x')` for named arguments in stubs
///   - Resolves repository method return types and emits correct stub values:
///       void / Future<void>  → null
///       primitives           → literal (e.g. '', 0, false)
///       nullable types       → null
///       custom entity types  → ClassName.empty()
class TestGenerator {
  /// Creates a generator.  [projectRoot] is needed to locate repository
  /// interface files for return-type resolution.
  TestGenerator({required this.projectRoot});

  /// Absolute path to the Flutter project root.
  final String projectRoot;

  final _fmt =
      DartFormatter(languageVersion: DartFormatter.latestLanguageVersion);

  /// Generates a test file for the provided [notifier].
  String generate(NotifierInfo notifier) {
    final buf = StringBuffer();

    _imports(buf, notifier);
    _mocks(buf, notifier);
    _mainBlock(buf, notifier);

    try {
      return _fmt.format(buf.toString());
    } catch (_) {
      // Return unformatted if there is a syntax error in the generated code.
      return buf.toString();
    }
  }

  // ── Imports ─────────────────────────────────────────────────────────────

  void _imports(StringBuffer b, NotifierInfo n) {
    b.writeln('// GENERATED BY mogen_unit_tests — YOU CAN REMOVE THIS COMMENT');
    b.writeln();
    b.writeln("import 'package:flutter_riverpod/flutter_riverpod.dart';");
    b.writeln("import 'package:flutter_test/flutter_test.dart';");
    b.writeln("import 'package:mocktail/mocktail.dart';");
    b.writeln();

    // Import the notifier itself.
    b.writeln("import '${n.importPath}';");

    // Import the state if available.
    if (n.stateInfo != null) {
      b.writeln("import '${n.stateInfo!.importPath}';");
    }

    // Import only repository interfaces from the current feature.
    final featureName = _extractFeatureName(n.importPath);
    final filteredRepos =
        _featureRepositories(n).where((r) => _isRepositoryInterface(r.type));

    for (final repo in filteredRepos) {
      final snakeCase = _toSnakeCase(repo.type);
      b.writeln(
          "import 'package:${n.packageName}/features/$featureName/domain/repositories/$snakeCase.dart';");
      b.writeln(
          "import 'package:${n.packageName}/features/$featureName/data/repositories/${snakeCase}_impl.dart';");
    }

    b.writeln();
  }

  // ── Mock classes ─────────────────────────────────────────────────────────

  void _mocks(StringBuffer b, NotifierInfo n) {
    final filteredRepos = _featureRepositories(n)
        .where((r) => _isRepositoryInterface(r.type))
        .toList();

    if (filteredRepos.isEmpty) return;

    b.writeln(
        '// ── Mocks ────────────────────────────────────────────────────');
    for (final repo in filteredRepos) {
      b.writeln(
          'class Mock${repo.type} extends Mock implements ${repo.type} {}');
    }
    b.writeln();
  }

  // ── main() ───────────────────────────────────────────────────────────────

  void _mainBlock(StringBuffer b, NotifierInfo n) {
    b.writeln('void main() {\n');
    b.write('TestWidgetsFlutterBinding.ensureInitialized();\n\n');
    _group(b, n);
    b.writeln('}');
  }

  void _group(StringBuffer b, NotifierInfo n) {
    final filteredRepos = _featureRepositories(n)
        .where((r) => _isRepositoryInterface(r.type))
        .toList();

    b.writeln("  group('${n.className}', () {");

    for (final repo in filteredRepos) {
      b.writeln('    late Mock${repo.type} mock${repo.type};');
    }
    b.writeln('    late ProviderContainer container;');
    b.writeln();

    _setUp(b, n, filteredRepos);
    _tearDown(b);

    // Filter out internal methods that start with 'p'.
    final publicMethods =
        n.methods.where((m) => !m.name.startsWith('p')).toList();

    for (final method in publicMethods) {
      _methodTests(b, method, n, filteredRepos);
    }

    b.writeln('  });');
  }

  // ── setUp ────────────────────────────────────────────────────────────────

  void _setUp(
      StringBuffer b, NotifierInfo n, List<RepositoryDep> filteredRepos) {
    b.writeln('    setUp(() {');

    for (final repo in filteredRepos) {
      b.writeln('      mock${repo.type} = Mock${repo.type}();');
    }

    b.writeln();
    b.writeln('      container = ProviderContainer(');

    if (filteredRepos.isNotEmpty) {
      b.writeln('        overrides: [');
      for (final repo in filteredRepos) {
        final provider =
            repo.providerExpression ?? '${_lcFirst(repo.type)}Provider';
        b.writeln(
            '          // Override the provider so the notifier gets mock${repo.type}');
        b.writeln('          $provider.overrideWithValue(mock${repo.type}),');
      }
      b.writeln('        ],');
    }

    b.writeln('      );');
    b.writeln('    });');
    b.writeln();
  }

  // ── tearDown ─────────────────────────────────────────────────────────────

  void _tearDown(StringBuffer b) {
    b.writeln('    tearDown(() {');
    b.writeln('      container.dispose();');
    b.writeln('    });');
    b.writeln();
  }

  // ── per-method tests ─────────────────────────────────────────────────────

  void _methodTests(StringBuffer b, MethodInfo method, NotifierInfo n,
      List<RepositoryDep> filteredRepos) {
    b.writeln(
        '    // ── ${method.name}() ──────────────────────────────────────');
    b.writeln("    group('${method.name}', () {");

    _methodSuccessTest(b, method, n, filteredRepos);

    b.writeln('    });');
    b.writeln();
  }

  void _methodSuccessTest(StringBuffer b, MethodInfo method, NotifierInfo n,
      List<RepositoryDep> filteredRepos) {
    final awaitKw = method.isAsync ? 'await ' : '';
    final notifierProvider = '${_lcFirst(n.className)}Provider';

    b.writeln("      test('${method.name} completes successfully', () async {");

    _stubOnlyCalledMethods(b, method, n, filteredRepos);

    if (method.params.isNotEmpty) {
      b.writeln();
      b.writeln('        // Arrange: inputs');
      for (final param in method.params) {
        final val = MockValueGenerator.forType(param.type);
        b.writeln('        final ${param.name} = $val;');
      }
    }

    b.writeln();
    b.writeln('        // Ensure notifier is initialised');
    b.writeln('        await container.read($notifierProvider.future);');

    b.writeln();
    b.writeln('        // Act');

    final args = _buildArgList(method.params);
    final call =
        '${awaitKw}container.read($notifierProvider.notifier).${method.name}($args)';

    if (method.returnType != 'void' && method.returnType != 'Future<void>') {
      b.writeln('        final result = $call;');
    } else {
      b.writeln('        $call;');
    }

    b.writeln();
    b.writeln('        // Assert');

    if (n.stateType != null &&
        n.stateType != 'dynamic' &&
        n.stateInfo != null) {
      b.writeln(
          '        final finalState = container.read($notifierProvider);');
      _generateStateFieldAssertions(b, method, n);
    } else {
      b.writeln('        // expect(container.read($notifierProvider), ...);');
    }

    b.writeln('      });');
    b.writeln();
  }

  // ── Generate state field assertions ──────────────────────────────────────

  void _generateStateFieldAssertions(
      StringBuffer b, MethodInfo method, NotifierInfo n) {
    if (n.stateInfo == null) return;

    final commonLoadingFields = ['isLoadingAction', 'isLoading', 'loading'];
    final commonErrorFields = ['error', 'errorMessage', 'errorMsg'];
    final commonSuccessFields = ['success', 'successMessage', 'message'];

    final stateFieldNames = n.stateInfo!.fields.map((f) => f.name).toSet();

    for (final field in commonLoadingFields) {
      if (stateFieldNames.contains(field)) {
        b.writeln('        expect(finalState.requireValue.$field, isFalse);');
        break;
      }
    }

    for (final field in commonErrorFields) {
      if (stateFieldNames.contains(field)) {
        b.writeln('        expect(finalState.requireValue.$field, isNull);');
        break;
      }
    }

    for (final field in commonSuccessFields) {
      if (stateFieldNames.contains(field)) {
        b.writeln('        expect(finalState.requireValue.$field, isNull);');
        break;
      }
    }
  }

  // ── Stub only methods actually called ────────────────────────────────────

  void _stubOnlyCalledMethods(
    StringBuffer b,
    MethodInfo method,
    NotifierInfo n,
    List<RepositoryDep> filteredRepos,
  ) {
    if (filteredRepos.isEmpty) return;

    b.writeln('        // Arrange: stub repositories');
    for (final repo in filteredRepos) {
      final calls = MethodCallDetector.detectRepositoryMethodCalls(
        n.sourceFilePath,
        repo.type,
        methodName: method.name,
      );

      if (calls.isEmpty) {
        b.writeln('        // No mocks needed for ${repo.type}');
      } else {
        final repoInterfacePath = _repositoryInterfacePath(repo, n);

        for (final call in calls) {
          b.writeln(
              '        when(() => mock${repo.type}.${call.invocationSource})');

          final returnType = MethodCallDetector.resolveReturnType(
            repoInterfacePath,
            call.methodName,
          );
          final returnVal = _stubReturnValue(returnType);
          b.writeln('            .thenAnswer((_) async => $returnVal);');
        }
      }
    }
  }

  // ── Stub return value resolution ─────────────────────────────────────────

  /// Returns a Dart literal suitable for the `thenAnswer` stub return value,
  /// derived from the repository method's declared [returnType].
  ///
  ///   - null / unknown                → `null`
  ///   - `void` / `Future<void>`       → `null`
  ///   - nullable types (`T?`)         → `null`
  ///   - primitive types               → literal (`''`, `0`, `false`, …)
  ///   - custom / entity class         → `ClassName.empty()`
  String _stubReturnValue(String? returnType) {
    if (returnType == null) return 'null';
    return MockValueGenerator.forReturnType(returnType);
  }

  /// Derives the absolute path to the domain repository interface file for
  /// the given [repo] dependency, based on the notifier's import path and
  /// the project root.
  String _repositoryInterfacePath(RepositoryDep repo, NotifierInfo n) {
    final featureName = _extractFeatureName(n.importPath);
    final snakeCase = _toSnakeCase(repo.type);
    return p.join(
      projectRoot,
      'lib',
      'features',
      featureName,
      'domain',
      'repositories',
      '$snakeCase.dart',
    );
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  String _buildArgList(List<ParamInfo> params) => params.map((p) {
        if (p.isNamed) return '${p.name}: ${p.name}';
        return p.name;
      }).join(', ');

  String _lcFirst(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  String _extractFeatureName(String importPath) {
    final parts = importPath.split('/');
    final featuresIdx = parts.indexOf('features');
    if (featuresIdx >= 0 && featuresIdx + 1 < parts.length) {
      return parts[featuresIdx + 1];
    }
    return '';
  }

  List<RepositoryDep> _featureRepositories(NotifierInfo n) {
    final featureName = _extractFeatureName(n.importPath);
    if (featureName.isEmpty) return const [];

    return n.repositories
        .where((repo) => _isFeatureRepository(repo.type, featureName))
        .toList();
  }

  bool _isFeatureRepository(String repoType, String featureName) {
    final normalizedRepo = repoType
        .replaceAll('Impl', '')
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '')
        .toLowerCase();

    final normalizedFeature =
        featureName.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '').toLowerCase();

    if (normalizedRepo.isEmpty || normalizedFeature.isEmpty) return false;
    if (normalizedRepo == normalizedFeature) return true;
    if (normalizedRepo.contains(normalizedFeature)) return true;

    final featureTokens = normalizedFeature
        .split(RegExp(r'[_\- ]+'))
        .where((token) => token.isNotEmpty)
        .toSet();

    return featureTokens.any((token) => normalizedRepo.contains(token));
  }

  bool _isRepositoryInterface(String type) {
    final lower = type.toLowerCase();
    return lower.endsWith('repository') &&
        !lower.contains('service') &&
        !lower.contains('datasource') &&
        !lower.contains('client') &&
        !lower.contains('api') &&
        !lower.contains('localauth');
  }

  String _toSnakeCase(String name) => name
      .replaceAllMapped(
        RegExp(r'([A-Z])'),
        (m) => '_${m.group(0)!.toLowerCase()}',
      )
      .replaceFirst(RegExp(r'^_'), '');
}
