// lib/src/generators/test_generator.dart

import 'package:dart_style/dart_style.dart';

import '../models/notifier_info.dart';
import '../utils/mock_value_generator.dart';

/// Generates a complete Mocktail + Riverpod test file for one [NotifierInfo].
///
/// Pattern used:
///   - ProviderContainer with overrides for each repository provider
///   - Mock<RepositoryType> for every detected repository
///   - Fake<ComplexType> + registerFallbackValue for every complex param type
///   - One success test and one error test per method (+ build)
class TestGenerator {
  final _fmt = DartFormatter();

  String generate(NotifierInfo notifier) {
    final buf = StringBuffer();

    _imports(buf, notifier);
    _mocks(buf, notifier);
    _fakes(buf, notifier);
    _mainBlock(buf, notifier);

    try {
      return _fmt.format(buf.toString());
    } catch (_) {
      return buf
          .toString(); // return unformatted if syntax error in generated code
    }
  }

  // ── Imports ─────────────────────────────────────────────────────────────

  void _imports(StringBuffer b, NotifierInfo n) {
    b.writeln('// GENERATED BY mogen_unit_tests — DO NOT EDIT');
    b.writeln('// ignore_for_file: lines_longer_than_80_chars');
    b.writeln();
    b.writeln("import 'package:flutter_riverpod/flutter_riverpod.dart';");
    b.writeln("import 'package:flutter_test/flutter_test.dart';");
    b.writeln("import 'package:mocktail/mocktail.dart';");
    b.writeln();
    b.writeln("import '${n.importPath}';");
    if (n.stateInfo != null) {
      b.writeln("import '${n.stateInfo!.importPath}';");
    }
    // Hint imports for repo types — developer fills these in
    for (final repo in n.repositories) {
      b.writeln('// TODO: import the file that declares ${repo.type}');
    }
    b.writeln();
  }

  // ── Mock classes ─────────────────────────────────────────────────────────

  void _mocks(StringBuffer b, NotifierInfo n) {
    if (n.repositories.isEmpty) return;
    b.writeln(
        '// ── Mocks ────────────────────────────────────────────────────');
    for (final repo in n.repositories) {
      b.writeln(
          'class Mock${repo.type} extends Mock implements ${repo.type} {}');
    }
    b.writeln();
  }

  // ── Fake classes ─────────────────────────────────────────────────────────

  void _fakes(StringBuffer b, NotifierInfo n) {
    final types = _complexParamTypes(n);
    if (types.isEmpty) return;

    b.writeln(
        '// ── Fakes (registerFallbackValue) ────────────────────────────');
    for (final t in types) {
      b.writeln('class Fake$t extends Fake implements $t {}');
    }
    b.writeln();
  }

  // ── main() ───────────────────────────────────────────────────────────────

  void _mainBlock(StringBuffer b, NotifierInfo n) {
    b.writeln('void main() {');
    _group(b, n);
    b.writeln('}');
  }

  void _group(StringBuffer b, NotifierInfo n) {
    b.writeln("  group('${n.className}', () {");

    // Field declarations
    for (final repo in n.repositories) {
      b.writeln('    late Mock${repo.type} mock${repo.type};');
    }
    b.writeln('    late ProviderContainer container;');
    b.writeln();

    _setUpAll(b, n);
    _setUp(b, n);
    _tearDown(b);

    // build() tests
    if (n.buildMethod != null) {
      _buildTests(b, n);
    }

    // Method tests
    for (final method in n.methods) {
      _methodTests(b, method, n);
    }

    b.writeln('  });');
  }

  // ── setUpAll ─────────────────────────────────────────────────────────────

  void _setUpAll(StringBuffer b, NotifierInfo n) {
    final types = _complexParamTypes(n);
    if (types.isEmpty) return;

    b.writeln('    setUpAll(() {');
    for (final t in types) {
      b.writeln('      registerFallbackValue(Fake$t());');
    }
    b.writeln('    });');
    b.writeln();
  }

  // ── setUp ────────────────────────────────────────────────────────────────

  void _setUp(StringBuffer b, NotifierInfo n) {
    b.writeln('    setUp(() {');

    // Instantiate mocks
    for (final repo in n.repositories) {
      b.writeln('      mock${repo.type} = Mock${repo.type}();');
    }

    b.writeln();
    b.writeln('      container = ProviderContainer(');

    if (n.repositories.isNotEmpty) {
      b.writeln('        overrides: [');
      for (final repo in n.repositories) {
        final provider =
            repo.providerExpression ?? '${_lcFirst(repo.type)}Provider';
        // Override the repository provider with the mock
        b.writeln(
            '          // Override the provider so the notifier gets mock${repo.type}');
        b.writeln('          $provider.overrideWithValue(mock${repo.type}),');
      }
      b.writeln('        ],');
    }

    b.writeln('      );');
    b.writeln('    });');
    b.writeln();
  }

  // ── tearDown ─────────────────────────────────────────────────────────────

  void _tearDown(StringBuffer b) {
    b.writeln('    tearDown(() {');
    b.writeln('      container.dispose();');
    b.writeln('    });');
    b.writeln();
  }

  // ── build() tests ────────────────────────────────────────────────────────

  void _buildTests(StringBuffer b, NotifierInfo n) {
    final stateType = n.stateType ?? 'dynamic';
    final notifierProvider = '${_lcFirst(n.className)}Provider';

    b.writeln("    // ── build() ────────────────────────────────────────────");
    b.writeln("    group('build', () {");

    // Success
    b.writeln("      test('returns $stateType successfully', () async {");
    _stubReposSuccess(b, n, returnType: stateType);
    b.writeln();
    b.writeln('        // Act');
    b.writeln('        final result = await container.read(');
    b.writeln('          $notifierProvider.future,');
    b.writeln('        );');
    b.writeln();
    b.writeln('        // Assert');
    b.writeln('        expect(result, isA<$stateType>());');
    _verifyRepos(b, n);
    b.writeln('      });');
    b.writeln();

    // Error
    b.writeln("      test('emits error when repository throws', () async {");
    _stubReposError(b, n);
    b.writeln();
    b.writeln('        // Act');
    b.writeln(
        '        final notifier = container.read($notifierProvider.notifier);');
    b.writeln('        await container.read($notifierProvider.future)');
    b.writeln(
        '            .catchError((_) => ${MockValueGenerator.forType(stateType)});');
    b.writeln();
    b.writeln('        // Assert');
    b.writeln('        expect(');
    b.writeln('          container.read($notifierProvider),');
    b.writeln('          isA<AsyncError>(),');
    b.writeln('        );');
    b.writeln('      });');
    b.writeln();

    b.writeln('    });');
    b.writeln();
  }

  // ── per-method tests ─────────────────────────────────────────────────────

  void _methodTests(StringBuffer b, MethodInfo method, NotifierInfo n) {
    b.writeln(
        "    // ── ${method.name}() ──────────────────────────────────────");
    b.writeln("    group('${method.name}', () {");

    _methodSuccessTest(b, method, n);
    _methodErrorTest(b, method, n);

    b.writeln('    });');
    b.writeln();
  }

  void _methodSuccessTest(StringBuffer b, MethodInfo method, NotifierInfo n) {
    final awaitKw = method.isAsync ? 'await ' : '';
    final notifierProvider = '${_lcFirst(n.className)}Provider';

    b.writeln("      test('${method.name} completes successfully', () async {");

    // Stub repos
    _stubReposSuccess(b, n, returnType: n.stateType);

    // Declare input variables from method params only
    if (method.params.isNotEmpty) {
      b.writeln();
      b.writeln('        // Arrange: inputs');
      for (final param in method.params) {
        final val = MockValueGenerator.forType(param.type);
        b.writeln('        final ${param.name} = $val;');
      }
    }

    b.writeln();
    b.writeln('        // Ensure notifier is initialised');
    b.writeln('        await container.read($notifierProvider.future);');
    b.writeln();
    b.writeln('        // Act');

    final args = _buildArgList(method.params);
    final call =
        '${awaitKw}container.read($notifierProvider.notifier).${method.name}($args)';

    if (method.returnType != 'void' && method.returnType != 'Future<void>') {
      b.writeln('        final result = $call;');
      b.writeln();
      b.writeln('        // Assert');
      b.writeln('        expect(result, isNotNull);');
    } else {
      b.writeln('        $call;');
      b.writeln();
      b.writeln('        // Assert');
      b.writeln('        // Verify state changed or side-effects occurred:');
      b.writeln('        // expect(container.read($notifierProvider), ...);');
    }

    _verifyRepos(b, n);
    b.writeln('      });');
    b.writeln();
  }

  void _methodErrorTest(StringBuffer b, MethodInfo method, NotifierInfo n) {
    final notifierProvider = '${_lcFirst(n.className)}Provider';

    b.writeln(
        "      test('${method.name} handles error from repository', () async {");

    _stubReposError(b, n);

    if (method.params.isNotEmpty) {
      b.writeln();
      b.writeln('        // Arrange: inputs');
      for (final param in method.params) {
        final val = MockValueGenerator.forType(param.type);
        b.writeln('        final ${param.name} = $val;');
      }
    }

    b.writeln();
    b.writeln(
        '        // Ensure notifier is initialised (may already be error)');
    b.writeln(
        '        await container.read($notifierProvider.future).catchError((_) {});');
    b.writeln();

    final args = _buildArgList(method.params);
    b.writeln('        // Act & Assert');
    b.writeln('        expect(');
    b.writeln('          () async => container');
    b.writeln('              .read($notifierProvider.notifier)');
    b.writeln('              .${method.name}($args),');
    b.writeln('          throwsA(isA<Exception>()),');
    b.writeln('        );');
    b.writeln('      });');
    b.writeln();
  }

  // ── Stub helpers ─────────────────────────────────────────────────────────

  /// Emits `when(...).thenAnswer(...)` for each repo, with a valid return value.
  void _stubReposSuccess(
    StringBuffer b,
    NotifierInfo n, {
    String? returnType,
  }) {
    if (n.repositories.isEmpty) return;

    b.writeln('        // Arrange: stub repositories');
    for (final repo in n.repositories) {
      // We don't know the exact method name at codegen time, so we emit
      // a clear comment + a template the developer fills in.
      b.writeln(
          '        // Stub any method on mock${repo.type} that build() calls:');
      b.writeln('        // when(() => mock${repo.type}.someMethod(any()))');

      if (returnType != null &&
          returnType != 'void' &&
          returnType != 'dynamic') {
        final val = MockValueGenerator.forType(returnType);
        if (val.isNotEmpty) {
          b.writeln('        //     .thenAnswer((_) async => $val);');
        } else {
          b.writeln(
              '        //     .thenAnswer((_) async => /* $returnType instance */);');
        }
      } else {
        b.writeln(
            '        //     .thenAnswer((_) async => /* return value here */);');
      }
    }
  }

  void _stubReposError(StringBuffer b, NotifierInfo n) {
    if (n.repositories.isEmpty) return;

    b.writeln("        // Arrange: make repository throw");
    for (final repo in n.repositories) {
      b.writeln('        // when(() => mock${repo.type}.someMethod(any()))');
      b.writeln("        //     .thenThrow(Exception('test error'));");
    }
  }

  void _verifyRepos(StringBuffer b, NotifierInfo n) {
    if (n.repositories.isEmpty) return;
    b.writeln();
    for (final repo in n.repositories) {
      b.writeln(
          '        // verify(() => mock${repo.type}.someMethod(any())).called(1);');
    }
  }

  // ── Utilities ─────────────────────────────────────────────────────────────

  /// Collects all complex (non-primitive) types used in method params
  /// that need a Fake class for registerFallbackValue.
  Set<String> _complexParamTypes(NotifierInfo n) {
    final types = <String>{};

    void collect(String rawType) {
      final t = rawType.replaceAll('?', '').trim();
      if (t.startsWith('List<')) {
        final inner = RegExp(r'List<(.+)>').firstMatch(t)?.group(1);
        if (inner != null) collect(inner);
        return;
      }
      if (!MockValueGenerator.isPrimitive(t) &&
          !t.startsWith('Future') &&
          !t.startsWith('Stream') &&
          t != 'dynamic') {
        types.add(t);
      }
    }

    for (final m in n.methods) {
      for (final p in m.params) collect(p.type);
    }
    if (n.buildMethod != null) {
      for (final p in n.buildMethod!.params) collect(p.type);
    }
    // State field item types
    if (n.stateInfo != null) {
      for (final f in n.stateInfo!.fields) {
        if (f.isList && f.listItemType != null) collect(f.listItemType!);
      }
    }

    return types;
  }

  String _buildArgList(List<ParamInfo> params) => params.map((p) {
        if (p.isNamed) return '${p.name}: ${p.name}';
        return p.name;
      }).join(', ');

  String _lcFirst(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);
}
